input_features:
  - name: utterance
    type: text
    encoder:
      type: rnn
      cell_type: lstm
      reduce_output: null
    preprocessing:
      tokenizer: space

output_features:
  - name: tag
    type: sequence
    decoder:
      type: tagger
